### ISSUE TITLE
Error in `jekyll serve` and `jekyll build`

### ISSUE THREAD

**Issue by Shuvomoy** [clayh53/tufte-jekyll#9]
`jekyll serve` or `jekyll build` is giving me the following errors:

```
/var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find celluloid-0.16.1 in any of the sources (Bundler::GemNotFound)
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
	from /var/lib/gems/1.9.1/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
	from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
	from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/bin/jekyll:16:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by clayh53** [comment]
This looks like some murky Ruby version mismatch thing. I have no build issues and am running Ruby-2.2.0 using RVM.

**Comment by clayh53** [comment]
Some necessary bundles were yanked and are no longer available. 

Fix by running ```bundle update celluloid``` from the terminal

see [this discussion](http://stackoverflow.com/questions/32182273/error-in-celluloid-gem-installation) for more

**Comment by diogocapela** [comment]
Fixed by running `bundle`.
